    <section class="section section-lg bg-default">
        <div class="container">
            <h3>Convênios</h3>
            <br />
            <?php if (isset($this->resp) && !is_null($this->resp)) :?>
            <div class="alert">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <?=$this->resp?>
            </div>
            <?php endif;?>
            <table class="table table-ordered table-hover">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->convernios as $convernio) : ?>
                    <tr>
                        <td><?=$this->escape($convernio->id);?></td>
                        <td><?=$this->escape($convernio->descricao);?></td>
                        <td>
                            <a href="<?=$this->url(array('controller'=>'convernio','action'=>'edit', 'id'=>$convernio->id, 'edit' => 'false'));?>" class="btn btn-sm btn-primary">
                                Editar
                            </a>
                            <a href="<?=$this->url(array('controller'=>'convernio', 'action'=>'delete', 'id'=>$convernio->id));?>" class="btn btn-sm btn-primary">
                                Deletar
                            </a>
                        </td>
                    </tr>  
                    <?php endforeach; ?>         
                </tbody>
            </table>
            <div class="form-wrap form-wrap-button">
                <a href="<?=$this->url(array('controller' => 'convernio', 'action' => 'add'), null, true) ?>" class="btn btn-primary" role="button">Novo Convêrnio</a>
            </div>
        </div>
    </section>