    <section class="section section-custom-1 bg-default" style="border: 0px solid black">
        <div class="container" style="border: 0px solid black">
            <div class="row row-50" style="border: 0px solid black">
                <div class="col-xl-12" style="border: 0px solid black">
                  <div class="inset-4">
                    <div class="layout-1 wow fadeIn" style="border: 0px solid black">
                        <h2 class="text-uppercase font-weight-bold ">Alterar Serviço</h2>
                      <!-- <div class="layout-2-item"><a class="button button-sm button-style-1" href="#">Ver Todos</a></div> -->
                    </div>
                  </div>
                </div>
            </div> 
            <div class="row row-50" style="border: 0px solid black">
                <div class="col-xl-12" style="border: 0px solid black">
                  <div class="inset-4">
                    <div class="layout-1 wow fadeIn" style="border: 0px solid black">
                        <?php if (isset($this->resp) && !is_null($this->resp)) :?>
                        <div class="alert">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <?=$this->resp?>
                        </div>
                        <?php endif;?>
                    </div>
                  </div>
                </div>
            </div> 
            <div class="row row-50" style="border: 0px solid black">    
                <div class="col-sm-3 wow fadeIn text-left">
                    <!-- /section -->
                    <div class="section">
                        <!-- container --> 
                        <div class="container">
                            <!-- row --> 
                            <div class="row">
                                <div class="span12">          
                                    <div class="widget ">
                                        <div class="widget-content">
                                            <form action="<?=$this->url(array('controller' => 'servico', 'action' => 'edit'), null, true) ?>" method="POST">
                                                <div class="fields">
                                                    <div class="field">
                                                        <label for="descricao">Descrição</label>
                                                        <input type="text" id="descricao" name="descricao" size="50" placeholder="Convênio" value="<?=$this->servico["descricao"]?>" />
                                                        <input type="hidden" name="id" id="id" value="<?=$this->servico["id"]?>">
                                                        <input type="hidden" name="editar" id="editar" value="true">
                                                    </div>                                                      
                                                </div> 
                                                <br />
                                                <div class="actions">                             
                                                    <button type="subumit" class="btn btn-primary " name="salvarservico" id="salvarservico">Salvar Registro</button>
                                                    <a href="<?=$this->url(array('controller' => 'servico', 'action' => 'index'), null, true) ?>" class="btn btn-primary" role="button">Lista Registros</a>
                                                </div>                               
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>    
                            <!-- /row --> 
                        </div>
                        <!-- /container --> 
                    </div>
                </div>
            </div>
        </div>
    </section>