<?php $url = "http://localhost:8098/";?>
<?=$this->doctype() ?>
<html class="wide wow-animation" lang="pt-br">
<head>
    <?=$this->headTitle('Desafio Técnico') ?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width height=device-height initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="<?=$url?>tema/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,600,700,800,900%7CBaloo">
    <link rel="stylesheet" href="<?=$url?>tema/css/bootstrap.css">
    <link rel="stylesheet" href="<?=$url?>tema/css/fonts.css">
    <link rel="stylesheet" href="<?=$url?>tema/css/style.css">
</head>
<body>
    <div class="ie-panel">
        <a href="">
            <img src="<?=$url?>tema/images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.">
        </a>
    </div>
    <div class="preloader">
        <div class="preloader-inner">
            <div class="preloader-top">
                <div class="preloader-top-sun">
                    <div class="preloader-top-sun-bg"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-0"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-45"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-90"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-135"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-180"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-225"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-270"></div>
                    <div class="preloader-top-sun-line preloader-top-sun-line-315"></div>
                </div>
            </div>
            <div class="preloader-bottom">
                <div class="preloader-bottom-line preloader-bottom-line-lg"></div>
                <div class="preloader-bottom-line preloader-bottom-line-md"></div>
                <div class="preloader-bottom-line preloader-bottom-line-sm"></div>
                <div class="preloader-bottom-line preloader-bottom-line-xs"></div>
            </div>
        </div>
    </div>
    <div class="page">
    <header class="section page-header page-header-2 section-custom-1-ally">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
            <nav class="rd-navbar rd-navbar-creative" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-lg-stick-up-offset="155px" data-xl-stick-up-offset="155px" data-xxl-stick-up-offset="155px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
                <div class="rd-navbar-main-outer">
                    <div class="rd-navbar-main">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap, .rd-navbar-toggle-element">
                                <span class="rd-navbar-toggle-inner">
                                    <span class="rd-navbar-toggle-element"><span></span></span>
                                    <span class="rd-navbar-toggle-text on">Menu</span><span class="rd-navbar-toggle-text off">Close</span>
                                </span>
                            </button>
                            <!-- RD Navbar Brand-->
                            <div class="rd-navbar-brand">
                                <a class="brand" href="index.html">
                                    <img class="brand-logo-dark" src="<?=$url?>tema/images/logo-default-195x39.png" alt="" width="195" height="39"/>
                                    <img class="brand-logo-light" src="<?=$url?>tema/images/logo-inverse-195x39.png" alt="" width="195" height="39"/>
                                </a>
                            </div>
                        </div>
                        <div class="rd-navbar-aside-outer">
                            <button class="rd-navbar-aside-toggle" data-multitoggle="#rd-navbar-aside" aria-label="Aside Toggle">
                                <span></span>
                            </button>
                            <div class="rd-navbar-aside" id="rd-navbar-aside">
                                <ul class="rd-navbar-aside-list">
                                    <li><span class="icon mdi mdi-map-marker"></span>AV. Floriano Peixoto Nº 47</li>
                                    <li><span class="icon mdi mdi-phone"></span>(62) 9-8453-6141</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="rd-navbar-nav-wrap">
                        <!-- RD Navbar Nav-->
                        <ul class="rd-navbar-nav">
                            <li class="rd-nav-item active">
                                <a class="rd-nav-link" href="<?=$this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Home</a>
                            </li>
                            <li class="rd-nav-item">
                                <a class="rd-nav-link" href="<?=$this->url(array('controller' => 'servico', 'action' => 'index'), null, true) ?>">Serviços</a>
                            </li>
                            <li class="rd-nav-item">
                                <a class="rd-nav-link" href="<?=$this->url(array('controller' => 'convernio', 'action' => 'index'), null, true) ?>">Convênios</a>
                            </li>
                            <li class="rd-nav-item">
                                <a class="rd-nav-link" href="<?=$this->url(array('controller' => 'paciente', 'action' => 'index'), null, true) ?>">Pacientes</a>
                            </li>                  
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Jumbotron 3-->
        <div class="jumbotron-3">
            <div class="parallax-container jumbotron-3-inner context-dark" style="background-image:url(<?=$url?>tema/images/bg-image-01.jpg); background-repeat: no-repeat; background-size: 125%">  
                <div class="parallax-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-lg-7 col-xl-7">
                                <div class="unit jumbotron-3-title wow fadeIn">
                                    <div class="unit-left">
                                        <span class="icon linearicons-quote-open icon-lg"></span>
                                    </div>
                                    <div class="unit-body">
                                        <h5 class="font-weight-regular line-height-title" style="color: black;"></h5>
                                    </div>
                                </div>
                                <div class="jumbotron-3-text wow fadeIn" data-wow-delay=".1s">
                                    <h1 class="text-uppercase font-weight-strong text-decoration" style="color: black;"><br><span class="font-weight-light"></span></h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>